### PR TITLE
Remove custom babel config

### PR DESCRIPTION
**Pull request by darasus**
- remove dependency on `babel` to be able to enable `swc`
- fix import paths
- add `svgr` plugin

### CODE REVIEW

**Comment by pastelsky** [comment]
Does this improve our build / HMR times?

**Comment by darasus** [comment]
@pastelsky not a huge difference for build (but it's kinda sorta expected on a tiny project). Haven't checked with HMR.

Before:
```
________________________________________________________
Executed in   21.34 secs    fish           external
   usr time   35.41 secs  183.00 micros   35.41 secs
   sys time    4.27 secs  879.00 micros    4.27 secs
```

After:
```
________________________________________________________
Executed in   21.10 secs    fish           external
   usr time   32.98 secs  155.00 micros   32.98 secs
   sys time    7.31 secs  731.00 micros    7.31 secs
```

But I guess biggest benefit is no `bable` deps in your project and one step closer to `turbopack`.

**Review by pastelsky — APPROVED** [review]
LGTM

**Comment by pastelsky** [comment]
@darasus You'll have to fix up merge conflicts — I just merged a couple of PRs.

**Comment by darasus** [comment]
@pastelsky okay I think we're all green again

**Pull request merged**
