### PR TITLE
Add instructions to install dependencies

### PR DESCRIPTION
**Pull request by aviskarkc10**

### CODE REVIEW

**Comment by aviskarkc10** [comment]
@pastelsky didn't realize I had conflicts. I have fixed 'em

**Comment by pastelsky** [comment]
You seem to have some unrelated changes as well. Was that intended?

**Comment by aviskarkc10** [comment]
@pastelsky That's probably because I branched off from this branch #288

**Comment by pastelsky** [comment]
Hi @aviskarkc10, this PR seems out of date and has a couple of unrelated changes still. 
I believe that `yarn install` / `npm install` is a given for JS repos and needn't be added to the README specifically.

**Pull request closed without merging**
