### PR TITLE
Autofocus on input field!

### PR DESCRIPTION
**Pull request by itsfadnis**
Saves a click or tab before you get typing 🤷‍♂️

### CODE REVIEW

**Comment by tom-sherman** [comment]
Probably want to consider how this behaves on mobile - a keyboard popping up right after the page loads is not ideal.

**Comment by itsfadnis** [comment]
@tom-sherman good point 👍

**Comment by tom-sherman** [comment]
@itsfadnis I think it's still a good idea though for desktop, maybe you could take a crack at implementing it desktop only?

**Comment by pastelsky** [comment]
Thanks for the PR!

**Pull request merged**
